salon_site1/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),

]

salon_site1/config_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from salon_shop.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('salon_shop.urls', namespace='shop')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('user/', include('user.urls', namespace='user')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

salon_site1/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('history_orders/', views.history_orders, name='history_orders'),
    path('list_order_item/<int:order_id>/', views.list_order_item, name='list_order_item'),

]

salon_site1/salon_shop/urls.py
from django.urls import path
from . import views
from .views import about, base, index, new_in, pr, salon_kr

app_name = 'salon_shop'

urlpatterns = [
    path('', base, name='main_page'),
    path('about/', about, name='about'),
    path('index/', index, name='index'),
    path('new_in/', new_in, name='news'),
    path('product/', pr, name='product_list'),
    path('category/<category_slug>/', views.product_list, name='product_list_by_category'),
    path('product_detail/<slug:slug>/', views.product_detail, name='product_detail'),
    path('salon_kr/', salon_kr, name='salon_kr'),
    path('index/favorite_list/', views.favorite_list, name='favorite_list')
]

salon_site1/user/urls.py
from django.urls import path
from .views import ProfilePage, RegisterView, LoginView, LogoutView, ProfileInfo

app_name = 'user'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('profile/', ProfilePage.as_view(), name="profile"),
    path('profile_info/', ProfileInfo.as_view(), name='profile_info'),
    path('logged_out/', LogoutView.as_view(), name='logged_out'),
    path('register/', RegisterView.as_view(), name="register"),
]

salon_site1/order/models.py
from django.core.validators import RegexValidator
from django.db import models
from salon_shop.models import Product
from django.contrib.auth.models import User


class Order(models.Model):
    email_validator = RegexValidator(
        regex=r"^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|"
              r"(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$")

    ph_numb_validator = RegexValidator(regex=r"^((\+7|7|8)+([0-9]){10})$",
                                       message='Значение в поле "Телефон" должно '
                                               'состоять из 11 цифр от 0 до 9,'
                                               'где первая цифра - 7/+7 или 8')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Пользователь')
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    email = models.EmailField(validators=[email_validator])
    address = models.CharField(max_length=250, verbose_name='Адрес доставки')
    postal_code = models.CharField(max_length=20, verbose_name='Индекс')
    city = models.CharField(max_length=100, verbose_name='Город доставки')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True)
    telephone = models.CharField(validators=[ph_numb_validator], max_length=200, null=True, verbose_name='телефон')
    status = models.BooleanField(default=False)
    paid = models.BooleanField(default=False, verbose_name='Оплачен?')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Заказ №: {}'.format(self.id)

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE, verbose_name='Заказ №')
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.PROTECT,
                                verbose_name='ID продукта')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена на момент заказа')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

salon_site1/order/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'telephone', 'address', 'postal_code', 'city']

salon_site1/order/views.py
from django.contrib import auth
from django.shortcuts import render
from .models import OrderItem, Order
from salon_shop.models import Product
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):

    """Проверка формы на валидность и создание заказа """
    cart = Cart(request)

    if request.method == 'POST':
        user = auth.get_user(request)
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            order.user = user
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'],)

            cart.clear()
            return render(request, 'order/created.html', {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'order/create.html', {'cart': cart, 'form': form})


def history_orders(request):

    """ Вывод истории заказов пользователя """

    user = auth.get_user(request)
    history_list = Order.objects.get_queryset().filter(user_id=user.id)
    return render(request, 'order/history_orders.html',  {'history_list': history_list})


def list_order_item(request, order_id):

    """Вывод списка товаров в заказе"""

    list_order_items = OrderItem.objects.get_queryset().filter(order_id=order_id)
    list_prod_in_ord = []
    for item in list_order_items:
        product = Product.objects.get(id=item.product_id)
        prod_dict = {
            'id': product.id,
            'image': product.image,
            'name': product.name,
            'coast': item.price,
            'quantity': item.quantity
                     }
        list_prod_in_ord.append(prod_dict)
    return render(request, 'order/list_order_item.html', {'list_prod_in_ord': list_prod_in_ord})

salon_site1/order/templates/order/create.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% block content %}
<main class="main">
			<nav aria-label="breadcrumb" class="breadcrumb-nav">
				<div class="container">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
						<li class="breadcrumb-item active" aria-current="page">Оформление</li>
					</ol>
				</div>
			</nav>
		{% if user.is_authenticated %}
			<div class="container mb-6">
				<div class="row">
					<div class="col-lg-8">
						<ul class="checkout-steps">
							<li>
								<h2 class="step-title">Данные о доставке</h2>
								<form action="." method="post" class="order-form">
                                    {{ form.as_p }}
                                    <p><input type="submit" class="btn btn-primary float-right" value="Оформить"></p>
                                    {% csrf_token %}
                                </form>
							</li>
						</ul>
					</div><!-- End .col-lg-8 -->
					<div class="col-lg-4">
						<div class="order-summary">
							<h3>Итого</h3>
							<a data-toggle="collapse" href="#order-cart-section" class=""
							   role="button" aria-expanded="true" aria-controls="order-cart-section">
								{{ cart.get_total_price }} рублей
							</a>
                            <ul>
                                {% for item in cart %}
							        <div class="collapse show" id="order-cart-section" style="">
								        <table class="table table-mini-cart">
									        <tbody>
										        <tr>
											        <td class="product-col">
												        <figure class="product-image-container">
													        <a href="{% url 'salon_shop:product_detail' item.product.slug %}" class="product-image">
														        <img src="{{item.product.image.url}}" alt="product">
													        </a>
												        </figure>
												        <div>
													        <h2 class="product-title">
														        <a href="{% url 'salon_shop:product_detail' item.product.slug%}">{{item.product.name}}</a>
													        </h2>
													        <span class="product-qty">Кол-во:{{item.quantity}}</span>
												        </div>
											        </td>
											        <td class="price-col">{{item.total.price}}</td>
										        </tr>
                                            </tbody>
                                        </table>
                                    </div>
								{% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
			</div>
	{% else%}
		<div class="logo">
			<a href="{% url 'user:login' %} ">Войти в личный кабинет</a>
		</div>
	<div class="regist">
		<a href="{% url 'user:register' %}" >Регистрация</a>
	</div>
	{% endif %}
</main>
{% endblock %}

salon_site1/order/templates/order/created.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% block content %}
<main class="main">
			<nav aria-label="breadcrumb" class="breadcrumb-nav">
				<div class="container">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
						<li class="breadcrumb-item active" aria-current="page">Заказ</li>
					</ol>
				</div>
			</nav>
		<div class="container mb-5">
				<div class="row">
					<div class="col-lg-8">
    					<h1>Спасибо за заказ</h1>
    					<p>Вш заказ успешно оформлен. Номер вашего заказа <strong>{{ order.id }}</strong>.</p>
					</div>
				</div>
		</div>
</main>

{% endblock %}

salon_site1/order/templates/order/history_orders.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% block content %}
<main class="main">
	<nav aria-label="breadcrumb" class="breadcrumb-nav">
		<div class="container">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="index/"><i class="icon-home"></i></a></li>
				<li class="breadcrumb-item active" aria-current="page">Исторяи заказов</li>
			</ol>
		</div>
	</nav>
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="cart-table-container">
					<table class="table table-cart">
						<tbody>
						{% for order in history_list %}
							<tr >
								<td>Номер заказа: {{order.pk}}</td>
								<td>Адрес доставки: г.{{order.city}}, {{order.address}}, индекс {{order.postal_code}}</td>
								<td>Дата заказа: {{order.created}}</td>
								<td><a href="{% url 'order:list_order_item' order.pk %}">Посмотреть заказ</a></td>
								{% if order.status == True %}
									<td>Статус заказа: отправлен</td>
								{% else %}
									<td>Статус заказа: в рассмотрении </td>
								{% endif %}
							</tr>
						{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock content%}

salon_site1/order/templates/order/list_order_item.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% block title%} Корзина покупателя {% endblock title%}

{% block content %}
<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/index/"><i class="icon-home"></i></a></li>
                <li class="breadcrumb-item active" aria-current="page">Детали заказа</li>
            </ol>
        </div>
    </nav>
	<div class="container">
		<div class="row" >
			<div class="cart-table-container">
				<table class="table table-cart">
					<thead>
						<tr>
							<th class="product-col">Продукт</th>
							<th class="price-col">Цена</th>
							<th class="qty-col">Кол-во</th>
						</tr>
					</thead>
					<tbody>
						{% for item in list_prod_in_ord %}
							<tr class="product-row">
								<td class="product-col">
									<h2 class="product-title">
										<a>{{ item.name }}</a>
									</h2>
								</td>
								<td>{{ item.coast }}</td>
								<td>{{ item.quantity }}</td>

							</tr>
            			{% endfor %}
					</tbody>
				</table>
			</div><!-- End .cart-table-container -->
		</div><!-- End .row -->
	</div>
</main>
{% endblock %}