salon_site1/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),

]

salon_site1/config_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from salon_shop.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('salon_shop.urls', namespace='shop')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('user/', include('user.urls', namespace='user')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

salon_site1/favorites/urls.py
from django.urls import path
from . import views

app_name = 'favorites'

urlpatterns = [
    path("favorite/<int:pk>/", views.favorite_add, name='favorite_add'),
    path("favorite_remove/<int:pk>/", views.favorite_remove, name='favorite_remove'),
    path("favorite_detail/", views.favorite_detail, name='favorite_detail'),
]

salon_site1/salon_shop/urls.py
from django.urls import path
from . import views
from .views import about, base, index, new_in, pr, salon_kr

app_name = 'salon_shop'

urlpatterns = [
    path('', base, name='main_page'),
    path('about/', about, name='about'),
    path('index/', index, name='index'),
    path('new_in/', new_in, name='news'),
    path('product/', pr, name='product_list'),
    path('category/<category_slug>/', views.product_list, name='product_list_by_category'),
    path('product_detail/<slug:slug>/', views.product_detail, name='product_detail'),
    path('salon_kr/', salon_kr, name='salon_kr'),
    path('index/favorite_list/', views.favorite_list, name='favorite_list')
]

salon_site1/favorites/models.py
from django.db import models
from django.contrib.auth.models import User
from salon_shop.models import Product


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    product = models.ForeignKey(Product,  on_delete=models.CASCADE, verbose_name='Товар')

salon_site1/favorites/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import auth
from .models import Favorite
from salon_shop.models import Product


def get_favorite_list(user):

    """Получение избранных товаров для конкретного пользователя"""

    return Favorite.objects.get_queryset().filter(user=user)


def favorite_add(request, pk):

    """Добавление избранных товаров"""

    user = auth.get_user(request)
    product = get_object_or_404(Product, id=pk)
    Favorite.objects.get_or_create(user=user, product=product)
    return render(request, 'favorite.html', {'favorite_list': get_favorite_list(user)})


def favorite_remove(request, pk):

    """Удаление избранных товаров"""

    user = auth.get_user(request)
    product = get_object_or_404(Product, id=pk)
    Favorite.objects.filter(user=user, product=product).delete()
    return render(request, 'favorite.html', {'favorite_list': get_favorite_list(user)})


def favorite_detail(request):

    """Вывод всех избранных товаров"""

    user = auth.get_user(request)
    return render(request, 'favorite.html', {'favorite_list': get_favorite_list(user)})


def favorite_list(request):

    """Получение списка избранного для JQ"""

    user = auth.get_user(request)
    return render(request, 'favorite_list.html', {'favorite_list': get_favorite_list(user)})

salon_site1/favorites/templates/favorite.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% block content %}
<main class="main">
	<nav aria-label="breadcrumb" class="breadcrumb-nav">
		<div class="container">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
				<li class="breadcrumb-item active" aria-current="page">Избранные товары</li>
			</ol>
		</div>
	</nav>
	<div class="container pb-4">
		<div class="row">
			{% include "favorite_list.html "%}
		</div>
	</div>
</main>
{% endblock %}

salon_site1/favorites/templates/favorite_list.html
    {% if user.is_authenticated and favorite_list != None %}
        {% for item in favorite_list %}
            <div class="collapse show" id="order-cart-section" style="">
                <table class="table table-mini-cart">
                    <tbody>
                        <tr>
                            <td class="product-col">
                                <figure class="product-image-container">
                                    <a href="{% url 'salon_shop:product_detail' item.product.slug %}" class="product-image">
                                        <img src="{{item.product.image.url}}" alt="product">
                                    </a>
                                </figure>
                                <div>
                                    <h2 class="product-title">
                                        <a href="{% url 'salon_shop:product_detail' item.product.slug%}">{{item.product.name}}</a>
                                    </h2>
                                </div>
                            </td>
                        </tr>
                        <tr class="product-action-row">
                            <td colspan="4" class="clearfix">
                                <div class="float-center">
                                    <a href="{% url 'favorites:favorite_remove' item.product.pk %}" >Удалить</a>
                                </div><!-- End .float-right -->
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        {% endfor %}
    {% else %}
    <div>
        <h4> Нет избранных товаров </h4>
    </div>
    {% endif %}