salon_site1/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),

]

salon_site1/config_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from salon_shop.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('salon_shop.urls', namespace='shop')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('user/', include('user.urls', namespace='user')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

salon_site1/favorites/urls.py
from django.urls import path
from . import views

app_name = 'favorites'

urlpatterns = [
    path("favorite/<int:pk>/", views.favorite_add, name='favorite_add'),
    path("favorite_remove/<int:pk>/", views.favorite_remove, name='favorite_remove'),
    path("favorite_detail/", views.favorite_detail, name='favorite_detail'),
]

salon_site1/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('history_orders/', views.history_orders, name='history_orders'),
    path('list_order_item/<int:order_id>/', views.list_order_item, name='list_order_item'),

]

salon_site1/salon_shop/urls.py
from django.urls import path
from . import views
from .views import about, base, index, new_in, pr, salon_kr

app_name = 'salon_shop'

urlpatterns = [
    path('', base, name='main_page'),
    path('about/', about, name='about'),
    path('index/', index, name='index'),
    path('new_in/', new_in, name='news'),
    path('product/', pr, name='product_list'),
    path('category/<category_slug>/', views.product_list, name='product_list_by_category'),
    path('product_detail/<slug:slug>/', views.product_detail, name='product_detail'),
    path('salon_kr/', salon_kr, name='salon_kr'),
    path('index/favorite_list/', views.favorite_list, name='favorite_list')
]

salon_site1/user/urls.py
from django.urls import path
from .views import ProfilePage, RegisterView, LoginView, LogoutView, ProfileInfo

app_name = 'user'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('profile/', ProfilePage.as_view(), name="profile"),
    path('profile_info/', ProfileInfo.as_view(), name='profile_info'),
    path('logged_out/', LogoutView.as_view(), name='logged_out'),
    path('register/', RegisterView.as_view(), name="register"),
]

salon_site1/salon_shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Название')
    slug = models. SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('salon_shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.PROTECT, verbose_name='Категория')
    name = models.CharField(max_length=150, db_index=True)
    slug = models.CharField(max_length=150, db_index=True, unique=True)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True, verbose_name='Фото')
    stock = models.PositiveIntegerField()
    description = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    uploaded = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    class Meta:
        ordering = ('name',)
        verbose_name = "Товар"
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        """Для автоматической генерации слагов"""
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('salon_shop:product_detail', args=[self.pk, self.slug])


class News(models.Model):
    title = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(blank=True, verbose_name='Контент') #blank-значит заполнение необязательно
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации') #autonowadd-запол автомати при кажд сохранении записи autonow-сохр время и дату 1 раз при создании
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото', blank=True) # blank=true -не обяз к заполн, image-загружает только расширения картинки file-любое расширение
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано ли?')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post", kwargs={"post_id": self.pk})

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"
        ordering = ['-created_at']

salon_site1/salon_shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, News
from django.http import HttpResponseNotFound, HttpResponse, HttpResponseRedirect
from cart.forms import CartAddProductForm
from favorites.views import favorite_list


def product_list(request, category_slug=None):

    """Получение списка товаров по категории """

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    cart_product_form = CartAddProductForm()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'salon_shop/product_list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products,
                      'cart_product_form': cart_product_form
                  })


def product_detail(request, slug):

    """Получение детальной информации по товару"""

    product = get_object_or_404(Product,  slug=slug,  available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'salon_shop/product_detail.html', {'product': product,
                                                              'cart_product_form': cart_product_form})


def pr(request):

    """Получение списка товаров"""

    products = Product.objects.all()
    cart_product_form = CartAddProductForm()
    context = {
        'products': products,
        'title':'Продукция',
        'cart_product_form': cart_product_form,
    }
    return render(request, 'salon_shop/product_list.html', context=context)


def about(request):

    """информация о магазине"""

    return render(request, "salon_shop/about.html")


def base(request):
    return HttpResponseRedirect("/index/")


def index(request):
    """Вывод главной страницы"""

    return render(request, "salon_shop/index.html", {'title':'Главная страница'})


def new_in(request):

    """Вывод списка новостей"""

    news = News.objects.all()
    context = {
        'news': news,
        'title': "Новости, скидки,акции"

    }
    return render(request, 'salon_shop/news.html', context=context)


def salon_kr(request):
    return render(request, 'salon_shop/salon_kr.html', {'title':" О салоне красоты"})


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h2>Ошибка 404</h2>,\n <h1>Страница не найдена</h1>'
                                ',\n<h3>Проверьте, правильно ли Вы ввели адрес. Правильно?\nТогда, '
                                'возможно, на странице идут технические работы</h3>')

salon_site1/salon_shop/templates/salon_shop/about.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% block content %}
<main class="main">
			<div class="container mt-2 pt-0">
				<div class="outer-container page-header page-header-bg text-left" style="background: 70%/cover #D4E1EA url('{% static 'salon_shop/images/page-header-bg.jpg' %}');">
					<div class="container pl-5">
						<h1><span>О нас</span>
							НАША КОМПАНИЯ</h1>
					</div><!-- End .container -->
				</div><!-- End .page-header -->
			</div><!-- End .container -->
			<nav aria-label="breadcrumb" class="breadcrumb-nav">
				<div class="container">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/index"><i class="icon-home"></i></a></li>
						<li class="breadcrumb-item active" aria-current="page">О магазине</li>
					</ol>
				</div><!-- End .container -->
			</nav>
			<div class="conteiner-info">
				<div class="container pt-0">
						<div class="about-section">
							<h2 class="subtitle"> Наша история </h2>
							<p>Интернет-магазин "САЛОН КРАСОТЫ" создан для того, чтобы удовлетворять потребности российских девушек (и мужчин) в желании быть красивыми и использовать профессиональную косметику для ухода за своими волосами. Наши цели и принципы можно сформулировать несколькими тезисами:</p>
							<p><a>Профессионализм</a> Наш магазин продаёт именно профессиональную косметику, которая обычно используется в хороших салонах красоты. Теперь вы можете позволить себе применять её и у себя дома!</p>
							<p><a>Надёжность</a> Мы не склонны к сотрудничеству с сомнительными поставщиками косметической продукции. В оригинальности и качестве нашей продукции можно не сомневаться благодаря тому, что мы продаём только те марки косметики, которые зарекомендовали себя с наилучшей стороны среди профессионалов, и, в отличие неофициальных или даже нелегальных перекупщиков, мы работаем от имени юридического лица и напрямую с крупными и надёжными поставщиками из России, Великобритании, Испании, США.</p>
							<p><a>Эксклюзивность</a>. Помимо того, что всю без исключения нашу продукцию сейчас сложно найти в магазинах, а в салонах красоты она продаётся по заоблачным ценам, некоторые позиции нашего ассортимента можно на данный момент в России купить только у нас! Мы стараемся не только следить за текущими тенденциями спроса, но и знакомить жительниц России с новыми для нашей страны товарами, которые в ближайшем будущем могут получить широкое распространение.</p>
							<p><a>Отличные цены</a> Наша продукция стоит гораздо дешевле, чем у других. В отличие от салонов красоты и реальных магазинов, мы освобождены от необходимости платить за аренду торговых площадей. Кроме того, как уже упоминалось выше, мы работаем без лишних посредников и поставляем в основном продукцию, пользующуюся наибольшим спросом. Это позволяет экономить на содержании большого склада и держать наши цены на самом низком уровне - чаще всего ниже, чем у всех конкурентов. Дальнейшее снижение цены уже вряд ли возможно без появления сомнений в надёжности продавца.</p>
							<p class="lead">Таким образом, покупая продукцию у нас, вы можете быть уверены, что покупаете лучшие средства для ухода за телом, от самых надёжных поставщиков, и по самым низким ценам! </p>
						</div><!-- End .about-section -->
					</div><!-- End .container -->
			</div>
</main>
{% endblock content %}

salon_site1/salon_shop/templates/salon_shop/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8" />
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'salon_shop/images/icons/favicon.ico' %}">
    <script src="{% static 'salon_shop/js/webfont.js' %}" async=""></script>
    <script type="text/javascript">
		WebFontConfig = {
			google: { families: [ 'Open+Sans:300,400,600,700,800','Poppins:300,400,500,600,700,800' ] }
		};
		(function(d) {
			var wf = d.createElement('script'), s = d.scripts[0];
			wf.src = 'static/salon_shop/js/webfont.js';
			wf.async = true;
			s.parentNode.insertBefore(wf, s);
		})(document);
	</script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="{% static 'salon_shop/css/bootstrap.min.css'%}">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="{% static 'salon_shop/css/style.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'salon_shop/css/animate.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'salon_shop/vendor/fontawesome-free/css/all.min.css'%}">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CPoppins:300,400,500,600,700,800" media="all">
    <title>Интернет-магазин</title>
</head>
<body>
<header class="header mb-0">
    <div class="header-middle">
        <div class="container">

            <div class="header-left">
                <button class="mobile-menu-toggler mr-2" type="button">
                    <i class="icon-menu"></i>
                </button>
                <a href="/index/" class="logo">
                    <img src="{% static 'salon_shop/images/logo.png' %}" alt="Logo" width="300" height="150">
                </a>
            </div><!-- End .header-left -->

            <div class="header-right">
                <div class="header-contact d-none d-lg-flex ml-5">
                    <i class="icon-phone-2"></i>
                    <h6>Позвони сейчас<a href="tel:#" class="font1 text-secondary">+89140000000</a></h6>
                </div>
                {% if user.is_authenticated %}
                <div>
                    <a href="{% url 'user:profile' %}" class="header-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                             class="bi bi-person-lines-fill" viewBox="0 0 16 16">
                            <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11
                            3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0 1h4a.5.5
                            0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0
                            1h2a.5.5 0 0 0 0-1h-2z"/>
                        </svg>
                    </a>
                </div>
                <div class="logout">
                    <a href="{% url 'user:logged_out' %} " class="header-icon "><i class="icon-user"  ></i></a>
                </div>
                <div>
                    <a href="{% url 'favorites:favorite_detail' %}" class="header-icon" ><i class="icon-wishlist-2"></i></a>
                </div>
                {%else%}
                <div class="logo">
                    <a href="{% url 'user:login' %} " class="header-icon "><i class="icon-user"  ></i></a>
                </div>
                <div class="regist">
                    <a href="{% url 'user:register' %}" class="header-icon "><i class="icon-user-2" ></i></a>
                </div>
                {% endif %}
                <div class="dropdown cart-dropdown">
                    <a href=/cart/ class="cart" >
                        <i class="icon-shopping-cart"></i>
                    </a>
                </div>
            </div>
        </div>
    <div class="sticky-wrapper">
        <div class="header-bottom mb-lg-2 sticky-header" data-sticky-options="{
				'move': [
					{
						'item': '.header-icon:not(.search-toggle)',
						'position': 'end',
						'clone': false
					},
					{
						'item': '.cart-dropdown',
						'position': 'end',
						'clone': false
					}
				],
				'moveTo': '.container',
				'changes': [
					{
						'item': '.logo-white',
						'removeClass': 'd-none'
					},
					{
						'item': '.header-icon:not(.search-toggle)',
                        'removeClass': 'pb-md-1',
                        'addClass': 'text-white'
					},
					{
						'item': '.cart-dropdown',
                        'addClass': 'text-white'
					}
				]
			}" style="margin-right: 17px;">
            <div class="container">
                <div class="logo logo-transition logo-white w-100 d-none">
                    <a href="/index">
                        <img src="{% static 'salon_shop/images/logo.png' %}" alt="Logo" width="110" height="46">
                    </a>
                </div>
                <div class="bg-dark w-100">
                    <nav class="main-nav">
                        <ul class="menu d-flex justify-content-center sf-js-enabled sf-arrows" style="touch-action: pan-y;">
                            <li class="active">
                                <a href="/index">Главная</a>
                            </li>
                            <li class="news">
                                <a href="/new_in">Новости</a>
                            </li>
                            <li>
                                <a href="/product" class="sf-with-ul">Каталог</a>
                                <div class="megamenu megamenu-fixed-width megamenu-3cols" style="display: none; left: -15px;">
                                    <div class="row">
                                        <div class="col-lg-4">
                                            <a class="nolink">Категории</a>
                                            <ul class="submenu">
                                                <li><a href="/category/volosy/">Волосы</a></li>
                                                <li><a href="/category/lico/">Лицо</a></li>
                                                <li><a href="/category/nogti/">Ногти</a></li>
                                                <li><a href="/category/rashodnye-materialy/">Расходные материалы</a></li>
                                                <li><a href="/category/telo/">Тело</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div><!-- End .megamenu -->
                            <li><a class="d-none d-xl-inline-block" href="/about">О магазине</a></li>
                            <li><a class="salon_kr" href="/salon_kr"> Салон красоты </a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    </div>
</header>
<!-- End .header -->
{% block content%}
{% endblock content%}
<footer>
    <div class="container">
        <div class="widget">
            <br/>
            <h3 class="widget-title">Помощь</h3>
            <hr width="100%" size="1" color="grey"/>
                 <ul class="contact info">
                    <div>
                        <li><span class="contact-info-label">Адрес магазина:</span>г. Хабаровск, ул.Ленина 8</li>
                        <li><span class="contact-info-label">Режим работы:</span><a>Ежедневно с 9:00 до 23:00</a></li>
                        <li><span class="contact-info-label">Email:</span> <a href="mailto:mail@example.com">mail@example.com</a><li>
                        <li><span class="contact-info-label">Телефон:</span>Звонок бесплатный <a href="тел:">+7(914)000-00-00</a></li>
                    </div>
                </ul>
        </div><!-- End .widget -->
    </div>
            <div class="container">
                <div class="social-icons">
                    <a href=" https://t.me/salon_kras_bot" class="social-icon social-telegram icon-telegram" target="_blank" title="Telegram">
                        <img src="{% static 'salon_shop/images/telegram.png' %}" alt="telegram" width="110" height="46"><a>Telegram-bot</a>
                    </a>
                </div>
            </div><!-- End .widget -->
        <div class="container">
            <div class="footer-middle">
                <div class="row">
                    <div class="col-lg-5 mb-4 mb-lg-0">
                        <div class="widget">
                            <h4 class="widget-title">Покупателям</h4>
                            <ul class="links link-parts row mb-0">
                                <div class="link-part col-md-6 col-sm-12">
                                    <li><a href="/about/">Об интернет-магазине</a></li>
                                    <li><a href="/salon_kr/">О салоне красоты</a></li>
                                    <li><a href="{% url 'user:profile' %}"> Личный кабинет</a></li>
                                </div>
                                <div class="link-part col-md-6 col-sm-12">
                                    <li><a href="{% url 'order:history_orders' %}">История заказов</a></li>
                                </div>
                            </ul>
                        </div>
                    </div><!-- End .col-lg-3 -->
                </div>
            </div><!-- End .col-lg-3 -->
        </div><!-- End .row -->
        <div class="container">
                <div class="footer-bottom d-flex justify-content-between align-items-center flex-wrap">
                    <p class="footer-copyright py-3 pr-4 mb-0">©2022 САЛОН КРАСОТЫ - ИНТЕРНЕТ-МАГАЗИН ПРОФЕССИОНАЛЬНЫХ КОСМЕТИЧЕСКИХ СРЕСТВ.
                    ВСЕ ПРАВА ЗАЩИЩЕНЫ</p>
                    <img src='{% static "salon_shop/images/payments.png" %}' alt="payment" width="240" height="52" class="footer-payments py-3">
                </div><!-- End .footer-bottom -->
        </div>
</footer>
        <a id="scroll-top" href="#top" title="Top" role="button" class="fixed"><i class="fas fa-chevron-up"></i></a>
        <!-- Plugins JS File -->
        <script src="{% static 'salon_shop/js/jquery.min.js' %}"></script>
        <script src="{% static 'salon_shop/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'salon_shop/js/plugins.min.js' %}"></script>
        <script src="{% static 'salon_shop/js/jquery.appear.min.js' %}"></script>
        <!-- Main JS File -->
        <script src="{% static 'salon_shop/js/main.min.js' %}"></script>
</body>
</html>

salon_site1/salon_shop/templates/salon_shop/index.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% load slider_tags %}
{% block content %}
<main class="main">
    {% slider_block %}
    <div class="container">
         <div class="row">
             <div class="col">
                 <div class="col-sm-11">
					<div class="product-default inner-quickview inner-icon">
                        <h4>Ваши избранные товары</h4>
                            <figure>
                                <script type="text/javascript">
                                    $( document ).ready(function() {
                                        $( "#favorite_list" ).load("favorite_list/");
                                    });
                                </script>
                                    <div id="favorite_list">

                                    </div>
                            </figure>
                    </div>
             </div>
         </div>
    </div>
</main><!-- End .main -->
{% endblock content %}

salon_site1/salon_shop/templates/salon_shop/index_base.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% load slider_tags %}
{% block content %}
<main class="main">
                {% slider_block %}
</main><!-- End .main -->
{% endblock content %}

salon_site1/salon_shop/templates/salon_shop/news.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% load contact_tags %}
{% block content %}
<main class="main">
	<div class="container">
		<nav aria-label="breadcrumb" class="breadcrumb-nav">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="/index"><i class="icon-home"></i></a></li>
				<li class="breadcrumb-item active" aria-current="page">Новости</li>
			</ol>
		</nav>
		{% for item in news %}
		<div class="post-body">
			<h2 class="post-title">
				<font color="#e9846b">{{item.title}}</font>
			</h2>
			<div class="post-content">
				<div class="row">
					<div class="col-sm-4">
						<div class="media">
							<img class="align-self-center mr-3" src="{{item.photo.url}}" width="230" height="230">
						</div>
					</div>
					<div class="col-sm-7">
						<p><h3 align="justify">{{ item.description }}</h3></p>
					</div>
				</div>
			</div><!-- End .post-content -->
			<div class="post-meta">
				<span><i class="icon-calendar"></i>{{item.created_at}}</span>
			</div><!-- End .post-meta -->
		</div>
		{% endfor %}
		<div class="newsletter-banner appear-animate">
			<div class="d-flex flex-wrap">
				{% contact_form %}
			</div>
		</div>
	</div>
</main>
{% endblock content %}

salon_site1/salon_shop/templates/salon_shop/product_detail.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% block content %}
<nav aria-label="breadcrumb" class="breadcrumb-nav">
	<div class="container">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="/index"><i class="icon-home"></i></a></li>
			<li class="breadcrumb-item active" aria-current="page">О товаре</li>
		</ol>
	</div><!-- End .container -->
</nav>
<div class="container">
	<div class="product-single-container product-single-default">
		<div class="row">
			<div class="col-md-3 product-single-gallery">
				<div class="prod-thumbnail owl-dots" id="carousel-custom-dots">
					<div class="owl-dot active">
						<img src="{{product.image.url }}">
					</div>
				</div>
			</div><!-- End .product-single-gallery -->
			<div class="col-md-7 product-single-details">
				<h1 class="product-title">{{ product.name }}</h1>
				<hr class="short-divider">
				<div class="price-box">
					<span class="product-price">{{product.price}}</span>
				</div><!-- End .price-box -->
				<div class="product-desc">
					<p>
						{{product.description}}
					</p>
				</div><!-- End .product-desc -->
				<hr class="divider">
				<div class="product-single-share">
					<label class="sr-only">Share:</label>
					<a href="{% url 'favorites:favorite_add' product.pk %}" class="add-wishlist"
					   title="Добавить в избранное">Добавить в избранное</a>
				</div><!-- End .product single-share -->
				<hr class="divider">
				<div class="product-action">
					<div class="cart">
						<form action="{% url 'cart:cart_add' product.pk %}" method="post">
							{{ cart_product_form }}
							{% csrf_token %}
							<input class="btn btn-dark add-cart icon-shopping-cart" type="submit" value="В корзину">
						</form>
					</div>
				</div><!-- End .product-action -->
			</div><!-- End .product-single-details -->
		</div><!-- End .row -->
	</div>
</div>
{% endblock content %}

salon_site1/salon_shop/templates/salon_shop/product_list.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% block content %}
<main class="main" xmlns="" xmlns="">
	<nav aria-label="breadcrumb" class="breadcrumb-nav">
		<div class="container">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="/index/"><i class="icon-home"></i></a></li>
				<li class="breadcrumb-item active" aria-current="page">Продукция</li>
			</ol>
		</div>
	</nav>
		<div class="container pb-4">
			<div class="row">
				{% for prod in products %}
				<div class="col-sm-4">
					<div class="product-default inner-quickview inner-icon">
						<figure>
							<a href="{% url 'salon_shop:product_detail' prod.slug%}">
								<img src="{{prod.image.url}}" >
							</a>
							<form action="{% url 'cart:cart_add' prod.pk %}" method="post">
								{{ cart_product_form }}
								{% csrf_token %}
								<input class="btn btn-dark add-cart icon-shopping-cart" type="submit" value="В корзину">
							</form>
						</figure>
						<div class="product-details">
							<div class="category-wrap">
								<div class="category-list">
									<a href="{% url 'salon_shop:product_list_by_category' prod.category.slug %}" class="product-category">{{prod.category}}</a>
								</div>
								{% if user.is_authenticated %}
									<a href="{% url 'favorites:favorite_add' prod.pk %}" class="btn-icon-wish">
										<i class="icon-heart"></i>
									</a>
								{% else %}
									<a href="{% url 'user:login' %} " class="btn-icon-wish"><i class="icon-heart" ></i></a>
								{% endif %}
							</div>
							<h2 class="product-title">
								<a href="{% url 'salon_shop:product_detail' prod.slug %}">{{prod.name}}</a>
							</h2>

							<div class="price-box">
								<span class="product-price">{{prod.price}} руб.</span>
							</div><!-- End .price-box -->
						</div><!-- End .product-details -->
					</div>
				</div><!-- End .col-sm-4 -->
				{% endfor %}
			</div>
		</div>
</main>
{% endblock content %}

salon_site1/salon_shop/templates/salon_shop/salon_kr.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% block content %}
<main class="main">
	<nav aria-label="breadcrumb" class="breadcrumb-nav">
		<div class="container">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="/index"><i class="icon-home"></i></a></li>
				<li class="breadcrumb-item active" aria-current="page">Салон красоты</li>
			</ol>
		</div>
	</nav>
    <div class="container">
		<div class="row">
        	<p> Страница в стадии разработки</p>
		</div>
    </div>
</main>
{% endblock content %}