salon_site1/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),

]

salon_site1/config_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from salon_shop.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('salon_shop.urls', namespace='shop')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('user/', include('user.urls', namespace='user')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

salon_site1/favorites/urls.py
from django.urls import path
from . import views

app_name = 'favorites'

urlpatterns = [
    path("favorite/<int:pk>/", views.favorite_add, name='favorite_add'),
    path("favorite_remove/<int:pk>/", views.favorite_remove, name='favorite_remove'),
    path("favorite_detail/", views.favorite_detail, name='favorite_detail'),
]

salon_site1/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('history_orders/', views.history_orders, name='history_orders'),
    path('list_order_item/<int:order_id>/', views.list_order_item, name='list_order_item'),

]

salon_site1/salon_shop/urls.py
from django.urls import path
from . import views
from .views import about, base, index, new_in, pr, salon_kr

app_name = 'salon_shop'

urlpatterns = [
    path('', base, name='main_page'),
    path('about/', about, name='about'),
    path('index/', index, name='index'),
    path('new_in/', new_in, name='news'),
    path('product/', pr, name='product_list'),
    path('category/<category_slug>/', views.product_list, name='product_list_by_category'),
    path('product_detail/<slug:slug>/', views.product_detail, name='product_detail'),
    path('salon_kr/', salon_kr, name='salon_kr'),
    path('index/favorite_list/', views.favorite_list, name='favorite_list')
]

salon_site1/cart/models.py
from django.db import models

# Create your models here.

salon_site1/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

salon_site1/cart/views.py
from django.shortcuts import redirect, render, get_object_or_404, HttpResponseRedirect
from django.views.decorators.http import require_POST
from salon_shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):

    """Добавление товара в корзину"""

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):

    """Удаление товара из корзины"""

    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):

    """Список товаров в корзине"""

    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart':cart})


def cart_clear(request):
    del request.session['cart']
    request.session.modified = True
    return HttpResponseRedirect("/cart")

salon_site1/cart/templates/cart/detail.html
{% extends 'salon_shop/base.html' %}
{% load static %}
{% block content %}
<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/index/"><i class="icon-home"></i></a></li>
                <li class="breadcrumb-item active" aria-current="page">Корзина</li>
            </ol>
        </div>
    </nav>
	<div class="container mb-6">
		<div class="row">
			<div class="col-lg-8">
			<div class="cart-table-container">
				<table class="table table-cart">
					<thead>
						<tr>
							<th class="product-col">Продукт</th>
							<th class="price-col">Цена</th>
							<th class="qty-col">Кол-во</th>
							<th>Цена за 1шт</th>
							<th>Итог </th>
						</tr>
					</thead>
					<tbody>
						{% for item in cart %}
                			{% with product=item.product %}
					<tr class="product-row">
						<td class="product-col">
							<figure class="product-image-container">
								<a href="{% url 'cart:detail' % }">
									<img src="
									{% if product.image %}
                                        {{ product.image.url }}
                                    {% else %}
                                        {% static 'images/no_image.png' %}
                                    {% endif %}">
                            	</a>
							</figure>
							<h2 class="product-title">
								<a>{{ product.name }}</a>
							</h2>
						</td>
						<td>{{ item.price }}</td>
						<td>{{ item.quantity }}</td>
						<td>{{ item.price }}</td>
						<td class="num">{{ item.total_price }}</td>
                    </tr>
					<tr class="product-action-row">
						<td colspan="4" class="clearfix">
							<div class="float-left">
								<a href="{% url 'favorites:favorite_add' product.pk %}" class="btn-move">Добавить в избранное</a>
							</div><!-- End .float-left -->
							<div class="float-right">
								<a href="{% url 'cart:cart_remove' product.id %}" >Удалить</a>
							</div><!-- End .float-right -->
						</td>
					</tr>
							{% endwith %}
            			{% endfor %}
					</tbody>
					<tfoot>
						<tr>
							<td colspan="4" class="clearfix">
								<div class="float-left">
									<a href="{% url 'salon_shop:product_list' %}" class="button light">Продолжить покупки</a>
								</div><!-- End .float-left -->
							</td>
						</tr>
					</tfoot>
				</table>
			</div><!-- End .cart-table-container -->
					</div><!-- End .col-lg-8 -->
			<div class="col-lg-4">
				<div class="cart-summary">
					<h3>Итого</h3>
					<table class="table table-totals">
						<tfoot>
						<tr>
							<td>Цена всего заказа</td>
							<td>{{ cart.get_total_price }}</td>
						</tr>
						</tfoot>
					</table>
					<div class="checkout-methods">
						<a href="{% url 'order:order_create' %}" class="btn btn-block btn-sm btn-primary">Перейти к оформлению</a>
					</div><!-- End .checkout-methods -->
				</div><!-- End .cart-summary -->
			</div><!-- End .col-lg-4 -->
		</div><!-- End .row -->
	</div>
</main>
{% endblock %}